In [1]:
import numpy as np

In [6]:
# 4 ways of Dot product
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(4).reshape(2,2)

print(arr1)
print(arr2)
print()

print("Way 1",np.dot(arr1, arr2))
print()

print("Way 2",arr1@arr2)
print()

print("Way 3",arr1.dot(arr2))
print()

print("Way 4",np.matmul(arr1, arr2))

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]

Way 1 [[ 2  3]
 [ 6 11]]

Way 2 [[ 2  3]
 [ 6 11]]

Way 3 [[ 2  3]
 [ 6 11]]

Way 4 [[ 2  3]
 [ 6 11]]


In [9]:
arr1 = np.arange(15).reshape(-1,1)
print("1-D array",arr1)
print()

arr2 = np.arange(15).reshape(5,3)
print("2-D array",arr2.reshape(-1,1))
print()

arr3 = np.arange(8).reshape(2,2,2)
print("3-D array",arr3.reshape(-1,1))

1-D array [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]

2-D array [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]

3-D array [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [11]:
# Broadcasting

arr1 = np.arange(4).reshape(1,4)
arr2 = np.arange(4).reshape(4,1)

print(arr1)
print(arr2)

print(arr1+arr2)


[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [15]:
arr1 = np.arange(4).reshape(1,4)
arr2 = np.arange(4).reshape(2,2)

print(arr1)
print(arr2)

print(arr1+arr2)  


[[0 1 2 3]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (1,4) (2,2) 

In [20]:
# view()........................

arr = np.arange(9).reshape(3,3)
view_arr = arr.view(np.int16).reshape(3,6)
print(f"Dimantion :{arr.ndim}, dtype :{arr.dtype}")
print(arr)
print()
print(f"Dimantion :{view_arr.ndim}, dtype :{view_arr.dtype}")
print(view_arr)



Dimantion :2, dtype :int32
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Dimantion :2, dtype :int16
[[0 0 1 0 2 0]
 [3 0 4 0 5 0]
 [6 0 7 0 8 0]]


In [24]:
# Copy()........................

a = np.array ( [2, 3, 4])
b = a
c = np.copy(a)
a[0] = 15
b[0] == b[0]   # this should be true because 'a' is asigned to 'b'
# b[0] == c[0]  this should be false because 'c' is deep copy of 'a'

True